rectangle_search: rectangle_search.o
	g++ -Wall -Werror -std=c++11 rectangle_search.o -o rectangle_search

rectangle_search.o: rectangle_search.cc 
	g++ -Wall -Werror -std=c++11 -c -o rectangle_search.o rectangle_search.cc 

clean:
	rm -f *o rectangle_search